hackathon/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hackathonapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hackathonapp/urls.py
from django.urls import path
from .views import *

app_name = 'hackathonapp'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('register/', RegistrationView.as_view(), name="registration"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('locationcategory/', LocationCategoryView.as_view(), name="locationcategory"),
    path('locationdetail/<int:pk>/detail/', LocationListView.as_view(), name="locationlist"),
    path('location/<int:pk>/detail/', LocationDetailView.as_view(), name="locationdetail"),
    path('profile/',ProfileView.as_view(),name="profile"),
    path('add-interest/', AddInterestView.as_view(), name="addinterest"),
    path('delete-interest/',DeleteInterestView.as_view(),name="delete-category")

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>    
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">  

  <link rel="stylesheet" type="text/css" href="{% static 'visitorstatic/css/bootstrap.min.css' %}">

  <style>
    body {
      width: 100%;
      height: 100%;
    }
  </style>

  {% block css %}

  {% endblock %}

</head>
</head>

<!-- NavBar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">
  Ghumna Jau
  <img class="mt-n1 ml-2" src="/static/visitorstatic/images/flag.jpg" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-menu" aria-controls="nav-menu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="nav-menu">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hackathonapp:locationcategory' %}">Location Category</a>
      </li>
      {% if request.user.is_authenticated %}

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="fa fa-user"></span>
          {{request.user}}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'hackathonapp:profile' %}">Profile</a>
          
          <a class="dropdown-item" href="/logout">Logout</a>
        </div>
      </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'hackathonapp:login' %}">Login</a>      
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'hackathonapp:registration' %}">Sign Up</a>      
        </li>
      {% endif %}


    </ul>
  </div>
</nav>
<!-- End Of NavBar -->
<div class="container">
  {% block content %}

  {% endblock %}
</div>

  <script src="{% static 'visitorstatic/js/jquery.min.js' %}"></script>

  <script src="{% static 'visitorstatic/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'visitorstatic/js/scripts.js' %}"></script>
</body> 
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <style>
    .content {
      position: absolute;
      width: 100%;
      height: 100%;
      top: 53px;
      left: 0;
    }
    .cover {
      width: 100%;
      height: 100vh;
      background: url("../static/visitorstatic/images/himalaya.jpg");
      background-size: cover;
      background-repeat: no-repeat;
      text-align: center;
      display: flex;
      justify-content: center;
      align-items: center;
      color: #fff;
    }

    .carousel-item img {
      width: 100%;
      height: 100%;
      background-size: cover;
    }
  </style>

  <div class="content">

    <div class="cover">
      <div class="welcome-text">
        <div class="d-flex mb-1">
          <h1 class="display-1 mr-3 mt-4">Visit Nepal 2020</h1>
          <img width="150" height="150" style="border-radius: 50%;" src="/static/visitorstatic/images/Visit-nepal-2020.jpg">
        </div>
        <span class="lead">Welcome to explore the beauty of our country and enjoy the real happiness due to the nature.</span>
        <br />
        <a class="btn btn-primary btn-lg" href="/locationcategory">Explore More</a>
      </div>
    </div>

    <div class="container py-4">
      <div class="row">
        <div class="col-12 col-md-6">
          <h1>Featured...</h1>
          <br />
          <span>Nepal is known as the land of majestic Himalayas and natural beauty. But it is equally a land of diversity and colorful festivals. There are many colorful festivals during monsoon season, which are celebrated on the basis of lunar calendar. If you are in Nepal during rainy season, being a part of these festivals can be a lifetime experience for you. Nag Panchami, Janai Purnima, Gai Jatra, Indra Jatra and Krishna Ashtami are five major monsoon festivals.</span>
        </div>
        <div class="col-12 col-md-6">
          <div class="carousel ml-auto slide border" data-ride="carousel" style="width: 27rem; border-radius: 10px;">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="/static/visitorstatic/images/pashupati.jpg" class="d-block w-100">
              </div>

              <div class="carousel-item">
                <img src="/static/visitorstatic/images/rara.jpg" class="d-block w-100">
              </div>

               <div class="carousel-item">
                <img src="/static/visitorstatic/images/religious.jpg" class="d-block w-100">
              </div>
               <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
            </div>
          </div>
        </div>
<div class="row" >
<h1>Your Interested Field</h1>  
  {% for category in categories %}
  <div class="col-md-4 mt-3 mb-3">
    <div class="card" style="width: 350px;">
      <img class="card-img-top" src="{{category.image.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover; width: 350px;">
      <div class="card-body">
        <h5 class="card-title"><a style="text-decoration: none !important" href="{% url 'hackathonapp:locationlist' category.id %}">{{category.title}}</a></h5>
      </div>
    </div>
  </div>
  {% endfor %}
</div>  

      </div>
    </div>
  </div>
{% endblock %}
          

templates/location.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1 class="text-center text-info" >{{location.title}}</h1><hr>

<div class="row">
	{% for location in locations%}
	<div class="col-md-4 mt-3 mb-3">
		<div class="card" style="width: 350px;">
			<img class="card-img-top" src="{{location.image.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover; width: 350px;">
			<div class="card-body">
				<h5 class="card-title"><a style="text-decoration: none !important" href="{% url 'hackathonapp:locationdetail' location.id %}">{{location.title}}</a></h5>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

{% endblock %}

templates/locationcategory.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<form method="GET" action="">
{% csrf_token %}
 <div class="container my-3 py-5 text-center">
	<h1>Location Category</h1> 
		
		<div class="input-group">
		<input class="form-control" placeholder="Search your location." name="title" title="title">
		<button class="btn btn-primary ml-2">Search</button>
		</div>

 </div>
</form>
<div class="row">
	{% for category in categories %}
	<div class="col-md-4 mt-3 mb-3">
		<div class="card" style="width: 350px;">
			<img class="card-img-top" src="{{category.image.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover; width: 350px;">
			<div class="card-body">
				<h5 class="card-title"><a style="text-decoration: none !important" href="{% url 'hackathonapp:locationlist' category.id %}">{{category.title}}</a></h5>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

{% endblock %}

templates/locationdetail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h3 style="text-align: center"><span style="color:green;font-weight:bold;">Title </span>: <span style="color:blue;font-weight:bold;">{{locationlist.title}}</span></h3>
<hr>

<div class="row">
<img  src="{{locationlist.image.url}}" class="img-fluid" style="height: 700px;width: 1200px; object-fit: cover;">
	
</div><br>
<!-- <div class="row"> -->
	<h4><span style="color:blue;font-weight:bold;">City  </span>: {{locationlist.city}}</h4>
	<br>
	<h4><span style="color:blue;font-weight:bold;">TouristGuider  </span>: {{locationlist.locationguider}}<span style="color:blue;font-weight:bold;"> <br>mobile</span>({{locationlist.locationguider.mobile}})</h4>
	<br>
	<h4><span style="color:blue;font-weight:bold;">Description </span>: {{locationlist.description}}</h4>

<!-- </div> -->
<hr>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="card mx-auto mt-4" style="width: 24rem;">
        <div class="card-header">
            <strong class="lead">Welcome to Login</strong>
        </div>
        <div class="card-body mt-n3">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Registration</h2>
                
<!--         	{% if error %}
            <li class="text-danger">password</li>
            {% endif %} -->
            <form method="POST" enctype="multipart/form-data">
             {% csrf_token %}
             {{ form.as_p }}
             <button class="btn btn-info w-100 primary">Login</button>

            </form>	
        </div>
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<script type="text/javascript">
.content{
  text-size:5;
}
</script>
 <h1>My profile</h1><br>
<div class="row">
 <hr>
 <div class="col-md-8">
 	
	
 <img src="{{visitor.photo.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover; width: 250px; border-radius: 50%;">
 <h4><span style="color:Blue"> Name </span>: {{visitor.name}}</h4>
 <h4><span style="color:Blue"> Address </span>: {{visitor.address}}</h4>
 </div>	
 <div class="col-md-4">
 	{% if cats %}
 	<div class="input-group mb-3">
	  <div class="input-group-prepend">
	     <button type="button" id="add-int" class="btn btn-secondary mr-2">Add</button>
	  </div>
	    <select class="custom-select" id="interests">
	      {% for cat in cats %}
	        <option value="{{cat.id}}">{{cat.title}}</option>
	      {% endfor %}
	    </select>
	   </div>
   
    {% endif %}
    <div class="content">
    <div class="table-responsive">

    {% if interests.count == 0 %}
    		<hr />
        	<span class="lead">No Interests Selected! Please select your interests.</span>
        {% else %}
      <table class="table table-striped">
        <thead>
          
      	<tr>
      		<th>SN</th>

      		<th>Title</th>
          <th>Action</th>
      	</tr>
        </thead>
        <tbody>
          {% for int in interests %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{int.title}}</td>
            <td><button class="btn btn-danger btn-sm delete-int" data-id="{{int.id}}">
            	<span class="fa fa-trash"></span>
            </button></td>
          </tr>
          {% endfor %}
        </tbody>
        {% endif %}
      </table>
    </div>
	 </div>
	
</div>
</div>

 <hr>
<script>
  
 
</script>	

 {% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card mx-auto mt-4" style="width: 24rem;">
        <div class="card-header">
            <strong class="lead">Welcome to Register</strong>
            <br />
            <small class="form-help">Please fill up all form to register.</small>
        </div>
        <div class="card-body mt-n3">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Registration</h2>
                
<!--         	{% if error %}
            <li class="text-danger">password</li>
            {% endif %} -->
            <form method="POST" enctype="multipart/form-data">
             {% csrf_token %}
             {{ form.as_p }}
             <button class="btn btn-info w-75 primary">Register</button>

            </form>	
        </div>
</div>
{% endblock %}